[build]
  command = "echo 'Nenhuma ação de compilação necessária'"
  publish = "Site_TCC/Web" # Diretório onde estão os arquivos a serem publicados

[[redirects]]
  from = "/*"
  to = "/index.php"
  status = 200
